# -*- coding: utf-8 -*-
"""Copia de CV_AutomatizacionB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s5yauDt8ta2GnRQM38IQdaqlwV4pDFqK

## VISION POR COMPUTADORA
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install tensorflow
# %pip install pyads
import numpy as np
from tensorflow.keras.models import load_model
import pyads
import cv2
import time
from collections import Counter


ipc = pyads.Connection('192.168.57.231.1.1', 851)
ipc.open()
model=load_model("best.pt")
cap = 1  # La cámara se inicializa solo cuando se necesita

from ultralytics import YOLO
import pyads
import cv2
import time
from collections import Counter
import torch

# ===========================
# ⚙️ CONFIGURACIÓN GENERAL
# ===========================

# PLC
ADS_NET_ID = '192.168.57.231.1.1'
ADS_PORT = 851
PLC_TRIGGER_VAR = 'VARIABLES.bVarBool'
PLC_OUTPUT_VAR  = 'VARIABLES.iVarInt'

# Cámara (DroidCam por IP)
# Si usas DroidCam como stream IP, la URL típica es:
#   http://IP:4747/video    (MJPEG)
CAMERA_SOURCE   = "http://10.101.1.180:4747/video"
FRAME_SLEEP     = 0.03   # pausa entre capturas (30 ms)

# Ventana de decisión
MAX_FRAMES           = 20     # máximo de frames a analizar por flanco
MAX_CAPTURE_DURATION = 2.0    # máximo tiempo (segundos) por ciclo de captura
MIN_PREDICTIONS      = 5      # mínimo de predicciones para tomar decisión
DOMINANCE_THRESHOLD  = 0.6    # % mínimo de dominancia para aceptar color (ej. 60%)

# YOLO
MODEL_PATH   = "best.pt"
YOLO_CONF    = 0.45           # 🔽 antes 0.6, ahora más permisivo
YOLO_DEVICE  = 0 if torch.cuda.is_available() else 'cpu'

# Mapeo modelo → lógica de color → PLC
MODEL_TO_COLOR = {
    "Amarrillo": "amarillo",
    "amarillo": "amarillo",
    "Azul": "azul",
    "azul": "azul",
    "Negro": "negro",
    "negro": "negro",
    "Rojo": "rojo",
    "rojo": "rojo",
    "Otros": "otros",        # clase "Otros" ≠ background
    "otros": "otros",
    "background": "background"
}

COLOR_TO_PLC_VALUE = {
    "amarillo": 1,
    "azul": 2,
    "negro": 3,
    "rojo": 4,
    "otros": 5,              # pieza desconocida / fuera de patrón
    "background": 5          # no se vio nada claro
}

# ===========================
# 🔌 CONEXIÓN PLC + MODELO
# ===========================

ipc = pyads.Connection(ADS_NET_ID, ADS_PORT)
ipc.open()
print("✅ Conectado al PLC Beckhoff")

print(f"🔍 Cargando modelo YOLO: {MODEL_PATH}")
model = YOLO(MODEL_PATH)
print("✅ Modelo YOLO cargado correctamente")
print("📋 Clases del modelo:", model.names)

# ===========================
# 🎯 PREDICCIÓN CON YOLO
# ===========================

def predict_image(frame, model):
    """
    Recibe un frame BGR, lo pasa a YOLO, y devuelve un color lógico:
    'amarillo', 'azul', 'negro', 'rojo', 'otros' o 'background'.
    """
    if frame is None or frame.size == 0:
        print("⚠️ Frame vacío, devolviendo background")
        return "background"

    try:
        # Dos intentos: conf normal y luego conf más bajo
        for conf_thr in [YOLO_CONF, 0.35]:
            results = model.predict(
                source=frame,
                conf=conf_thr,
                device=YOLO_DEVICE,
                verbose=False
            )
            detections = results[0].boxes

            if len(detections) == 0:
                continue  # probamos con un conf más bajo

            # Tomamos la detección con mayor confianza (primer elemento)
            cls_id = int(detections.cls[0])
            conf   = float(detections.conf[0])
            raw_label = model.names[cls_id]

            # Normalizamos el nombre de la clase
            label = MODEL_TO_COLOR.get(raw_label, "otros")

            print(f"🎯 YOLO (conf={conf_thr:.2f}): {raw_label} -> {label} (conf {conf:.2f})")
            return label

        # Si después de los dos intentos no se detectó nada
        print("⚠️ Sin detecciones incluso con conf bajo, devolviendo background")
        return "background"

    except Exception as e:
        print(f"❌ Error en predicción: {e}")
        return "background"

# ===========================
# 🎥 DETECCIÓN POR FLANCO
# ===========================

def open_camera(source):
    """
    Abre la cámara. 'source' puede ser:
      - índice entero (0, 1, 2) para webcam
      - string con URL (DroidCam IP, RTSP, etc.)
    """
    # Para streams IP suele ir bien así:
    cap = cv2.VideoCapture(source)
    if not cap.isOpened():
        print(f"❌ No se pudo abrir la cámara/fuente: {source}")
        return None
    print(f"✅ Cámara/fuente abierta: {source}")
    return cap

cap = None
prev_state = False

try:
    while True:
        # Leer estado actual del bit de trigger del PLC
        current_state = ipc.read_by_name(PLC_TRIGGER_VAR, pyads.PLCTYPE_BOOL)

        # Flanco de subida: FALSE -> TRUE
        if current_state and not prev_state:
            print("🚀 Flanco de subida detectado. Iniciando ciclo de captura...")

            # Abrir cámara (en este caso DroidCam IP)
            cap = open_camera(CAMERA_SOURCE)
            if cap is None:
                # No cámara → esperamos al siguiente flanco
                time.sleep(0.5)
                prev_state = current_state
                continue

            predicciones = []
            start_time = time.time()

            # Capturamos hasta MAX_FRAMES o hasta MAX_CAPTURE_DURATION
            while True:
                # Si PLC baja el bit, dejamos de capturar
                if not ipc.read_by_name(PLC_TRIGGER_VAR, pyads.PLCTYPE_BOOL):
                    print("🧯 Trigger bajado por el PLC. Terminando captura.")
                    break

                # Límite de tiempo
                elapsed = time.time() - start_time
                if elapsed > MAX_CAPTURE_DURATION:
                    print("⏱️ Tiempo máximo de captura alcanzado.")
                    break

                # Límite de frames
                if len(predicciones) >= MAX_FRAMES:
                    print("📸 Máximo de frames alcanzado.")
                    break

                ret, frame = cap.read()
                if not ret or frame is None:
                    print("⚠️ No se pudo capturar frame. Terminando ciclo.")
                    break

                # (Opcional) Mostrar el frame
                cv2.imshow("Detección de tapa (DroidCam)", frame)
                if cv2.waitKey(1) & 0xFF == ord('q'):
                    print("🚪 Salida manual con tecla 'q'.")
                    break

                # Hacemos la predicción
                color = predict_image(frame, model)
                predicciones.append(color)
                print(f"   → Predicción {len(predicciones)}: {color}")

                time.sleep(FRAME_SLEEP)

            # Decisión final basado en votación
            if len(predicciones) >= MIN_PREDICTIONS:
                contador = Counter(predicciones)
                color_mas_frecuente, count = contador.most_common(1)[0]
                fraccion = count / len(predicciones)

                print(f"\n📊 Predicciones totales: {len(predicciones)}")
                print(f"   Frecuencias: {contador}")
                print(f"   Dominante: {color_mas_frecuente} ({fraccion*100:.1f}%)")

                if fraccion < DOMINANCE_THRESHOLD:
                    print("⚠️ Dominancia baja, se toma como background.")
                    color_final = "background"
                else:
                    color_final = color_mas_frecuente
            else:
                print(f"⚠️ Muy pocas predicciones ({len(predicciones)}), se toma background.")
                color_final = "background"

            # Enviar resultado al PLC
            plc_value = COLOR_TO_PLC_VALUE.get(color_final, 5)
            ipc.write_by_name(PLC_OUTPUT_VAR, plc_value, pyads.PLCTYPE_INT)
            print(f"📤 Enviado a PLC: {plc_value} ({color_final})\n")

            # Liberar cámara
            if cap is not None:
                cap.release()
                cap = None
            cv2.destroyAllWindows()
            print("🛑 Fin de ciclo. Esperando próximo flanco...\n")

        # Actualizar estado anterior y pequeña pausa
        prev_state = current_state
        time.sleep(0.02)

except KeyboardInterrupt:
    print("🧨 Interrumpido manualmente (Ctrl+C).")

except Exception as e:
    print(f"💥 Error general: {e}")

finally:
    if cap is not None:
        cap.release()
    cv2.destroyAllWindows()
    ipc.close()
    print("🔚 Recursos liberados y conexión PLC cerrada.")